version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=user_db

  db:
    image: mysql:latest
    ports:
      - '33066:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
